import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp, readFile, writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {ReviewEngine} from '../engine.js';
import {sameOrigin} from '../host.js';
import C from '../core.cjs';

const sid = 'session-test-a', sid2 = 'session-test-b';
const cards = Array.from({length: 6}, (_, index) => ({ID: `test-${index + 1}`, Question: `示例问题 ${index + 1}`, A: '选项甲', B: '选项乙', C: '选项丙', D: '选项丁', Answer: 'C', Hint: '比较四个选项。', Source: 'textbooks/example.md > 测试章节', Explanation: '测试解释。', Tags: 'test'}));
async function setup(seed = cards) { const root = await mkdtemp(join(tmpdir(), 'dsh-socratic-test-')); await writeFile(join(root, 'cards.tsv'), C.exportTSV(seed)); const engine = await new ReviewEngine(root).init(); return {root, engine}; }
function act(engine, sessionId, view, action, extra = {}) { return engine.request(sessionId, {action, expectedRevision: view.revision, roundId: view.roundId, cardId: view.card?.id, ...extra}); }

test('empty project initializes a header-only project card file', async () => { const root = await mkdtemp(join(tmpdir(), 'dsh-socratic-empty-')); const engine = await new ReviewEngine(root).init(); assert.equal(engine.cards.length, 0); assert.match(await readFile(join(root, 'cards.tsv'), 'utf8'), /#columns:ID\tQuestion/); const view = await engine.request(sid, {action: 'start'}); assert.equal(view.total, 0); assert.equal(view.done, true); });
test('TSV lossless roundtrip and Basic output', async () => { const {engine} = await setup(); const copy = engine.cards.map(card => ({...card})); copy[0].Hint = '多行\n"引号"\tTAB'; assert.deepEqual(C.parse(C.exportTSV(copy)), copy); assert.equal(C.rows(C.exportBasic(copy))[0].length, 3); assert.throws(() => C.parse('a\tb')); });
test('session separation, wrong feedback, retry and restart restore full round', async () => { const {engine, root} = await setup(); let first = await engine.request(sid, {action: 'start'}); const second = await engine.request(sid2, {action: 'start'}); assert.equal(first.total, 5); first = await act(engine, sid, first, 'choose', {choice: 'A'}); assert.equal(first.feedbackKind, 'wrong'); assert.equal((await engine.request(sid2, {action: 'status'})).tried.length, 0); first = await act(engine, sid, first, 'choose', {choice: 'C'}); const resumed = await new ReviewEngine(root).init(); assert.deepEqual(await resumed.request(sid, {action: 'status'}), first); first = await act(resumed, sid, first, 'pass'); assert.equal(first.results[0].passed, false); assert.equal((await resumed.load(sid)).progress['test-1'].stage, 0); assert.equal((await resumed.request(sid2, {action: 'status'})).roundId, second.roundId); });
test('independent pass extends, stale revision/card rejected, close retains results', async () => { const {engine} = await setup(); let view = await engine.request(sid, {action: 'start'}); const stale = view; view = await act(engine, sid, view, 'choose', {choice: 'C'}); await assert.rejects(act(engine, sid, stale, 'skip'), /界面已更新/); await assert.rejects(act(engine, sid, view, 'pass', {roundId: 'bad'}), /轮次/); view = await act(engine, sid, view, 'pass'); assert.equal((await engine.load(sid)).progress['test-1'].stage, 1); view = await act(engine, sid, view, 'close'); assert.equal(view.open, false); assert.equal(view.results.length, 1); });
test('free practice does not alter schedule; hints prevent independent pass', async () => { const {engine} = await setup(); let first = await engine.request(sid, {action: 'start', practice: true}); first = await act(engine, sid, first, 'choose', {choice: 'C'}); await act(engine, sid, first, 'pass'); assert.equal(Object.keys((await engine.load(sid)).progress).length, 0); let second = await engine.request(sid2, {action: 'start'}); second = await act(engine, sid2, second, 'hint'); second = await act(engine, sid2, second, 'choose', {choice: 'C'}); second = await act(engine, sid2, second, 'pass'); assert.equal(second.results[0].passed, false); });
test('parallel duplicate submission only commits once', async () => { const {engine} = await setup(); const view = await engine.request(sid, {action: 'start'}); const all = await Promise.allSettled([act(engine, sid, view, 'skip'), act(engine, sid, view, 'skip')]); assert.equal(all.filter(result => result.status === 'fulfilled').length, 1); assert.equal((await engine.request(sid, {action: 'status'})).index, 1); });
test('different workspace roots isolate cards and state', async () => { const first = await setup(cards); const secondCards = [{...cards[0], ID: 'other-1', Question: '另一个项目的问题'}]; const second = await setup(secondCards); assert.equal(first.engine.cards.length, 6); assert.equal(second.engine.cards.length, 1); await first.engine.request(sid, {action: 'start'}); assert.equal((await second.engine.request(sid, {action: 'status'})).roundId, null); });
test('prototype-like card IDs remain data across disk roundtrip', async () => { const special = [{...cards[0], ID: '__proto__'}]; const {engine, root} = await setup(special); let view = await engine.request(sid, {action: 'start'}); view = await act(engine, sid, view, 'choose', {choice: 'C'}); await act(engine, sid, view, 'pass'); assert.equal((await engine.load(sid)).progress.__proto__.stage, 1); const next = await new ReviewEngine(root).init(); assert.equal((await next.load(sid)).progress.__proto__.stage, 1); assert.equal({}.stage, undefined); });
test('imports retain another session active snapshot', async () => { const {engine} = await setup(); const active = await engine.request(sid, {action: 'start'}); const idle = await engine.request(sid2, {action: 'status'}); const text = C.exportTSV([{...engine.cards[0], Question: '更新题干'}]); await act(engine, sid2, idle, 'import', {text}); assert.equal((await engine.request(sid, {action: 'status'})).card.question, active.card.question); assert.equal(engine.cards[0].Question, '更新题干'); });
test('path traversal and corrupted state fail closed', async () => { const {engine, root} = await setup(); await assert.rejects(engine.request('../x', {action: 'status'})); await writeFile(join(root, 'dsh-state.' + sid + '.json'), '{broken'); await assert.rejects(engine.request(sid, {action: 'start'})); assert.equal(await readFile(join(root, 'dsh-state.' + sid + '.json'), 'utf8'), '{broken'); });
test('HTTP origin rejects missing foreign and cross-site requests', () => { assert.equal(sameOrigin({headers: {host: '127.0.0.1:3080', origin: 'http://127.0.0.1:3080', 'sec-fetch-site': 'same-origin'}}), true); for (const headers of [{host: 'x'}, {host: 'x', origin: 'http://evil'}, {host: 'x', origin: 'http://x', 'sec-fetch-site': 'cross-site'}]) assert.equal(sameOrigin({headers}), false); });
