// Native DSH module-loader format, matching shipped Client bundles; no build step.
window.__ModuleLoader__.load({id:'dsh-socratic-teaching-system',factory(require){
const React=require('react'),h=React.createElement;
const css=`.durable-review{box-sizing:border-box;width:min(calc(100% - 32px),952px);margin:14px auto 12px;padding:10px 14px;border:1px solid #e1e4e8;border-radius:13px;background:white;color:#24272d;font:14px/1.5 system-ui;min-height:56px;max-height:min(68dvh,720px);overflow:auto;box-shadow:0 2px 10px #1418200c}.durable-review *{box-sizing:border-box}.durable-review button,.durable-review a{border:1px solid #d4d8de;border-radius:7px;padding:5px 10px;background:white;color:#30343b;font:inherit;line-height:1.4;cursor:pointer;text-decoration:none}.durable-review button:hover:not(:disabled){background:#f6f7f9}.durable-review button:disabled{opacity:.6;cursor:default}.durable-review button:focus-visible,.durable-review textarea:focus-visible{outline:3px solid #9eb4cc;outline-offset:2px}.durable-review .rv-toolbar{display:flex;align-items:center;gap:8px}.durable-review .rv-title{white-space:nowrap}.durable-review small{font-size:12px;color:#6b7280}.durable-review .rv-actions{display:flex;gap:6px;justify-content:flex-end;align-items:center;margin-left:auto;flex-wrap:wrap}.durable-review .rv-body{border-top:1px solid #eceef1;margin-top:8px;padding-top:6px}.durable-review h3{font-size:16px;margin:4px 0 6px;white-space:pre-wrap}.durable-review p{margin:6px 0;white-space:pre-wrap}.durable-review .rv-options{display:grid;grid-template-columns:1fr 1fr;gap:6px;margin:7px 0}.durable-review .rv-option{text-align:left;white-space:pre-wrap;overflow-wrap:anywhere}.durable-review .rv-option.wrong{background:#fff0ee;border-color:#c45b52;color:#8d2821;opacity:1}.durable-review .rv-option.correct{background:#e8f6ed;border-color:#3b8b64;color:#17613e;opacity:1;font-weight:650}.durable-review .rv-feedback{padding:6px 9px;border-radius:7px;font-weight:600}.durable-review .rv-feedback.correct{color:#17613e;background:#e8f6ed}.durable-review .rv-feedback.wrong,.durable-review .rv-error{color:#8d2821;background:#fff0ee}.durable-review .rv-feedback.hint{color:#6d4b12;background:#fff7df}.durable-review .rv-source{display:block;margin-top:6px}.durable-review textarea{width:100%;min-height:100px;background:white;color:#24272d;border:1px solid #d4d8de;padding:8px;font:12px/1.5 monospace}.durable-review details{margin-top:8px}.durable-review summary{cursor:pointer}.durable-review .rv-report{font:12px/1.5 monospace;white-space:pre-wrap}@media(max-width:700px){.durable-review{width:calc(100% - 24px);padding:10px}.durable-review .rv-toolbar{flex-wrap:wrap}.durable-review .rv-options{grid-template-columns:1fr}.durable-review .rv-actions{margin-left:auto}}`;
async function call(sessionId,args,signal){const r=await fetch('/api/socratic-teaching/review',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({sessionId,...args}),signal});const d=await r.json();if(!r.ok||d.error){const e=Error(d.error||'复习请求失败');e.enabled=d.enabled;throw e;}return d;}
function Panel(props){const sid=props.sessionId;const [v,setV]=React.useState(null),[error,setError]=React.useState(''),[loadError,setLoadError]=React.useState(''),[enrolled,setEnrolled]=React.useState(false),[busy,setBusy]=React.useState(false),[manage,setManage]=React.useState(false),[text,setText]=React.useState(''),[output,setOutput]=React.useState('');
 React.useEffect(()=>{let alive=true,pending=false;const abort=new AbortController();const tick=async()=>{if(pending)return;pending=true;try{const d=await call(sid,{action:'status'},abort.signal);if(alive){setV(old=>old?.enabled&&d.enabled&&old.revision>d.revision?old:d);setLoadError('');setEnrolled(d.enabled===true);}}catch(e){if(alive){setLoadError(e.message);if(e.enabled===true)setEnrolled(true);}}finally{pending=false;}};tick();const timer=setInterval(tick,1000);return()=>{alive=false;abort.abort();clearInterval(timer);};},[sid]);
 async function action(kind,extra={}){if(busy||!v?.enabled)return;setBusy(true);setError('');try{const d=await call(sid,{action:kind,expectedRevision:v.revision,roundId:v.roundId,cardId:v.card?.id,...extra});if(kind==='export')setOutput(d.text);else {setV(d);if(kind==='import'){setText('');setOutput('');}}}catch(e){setError(e.message);}finally{setBusy(false);}}
 function download(){const u=URL.createObjectURL(new Blob([output],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=u;a.download='anki-review.txt';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
 if(!v?.enabled)return enrolled&&loadError?h('section',{className:'durable-review'},h('strong',null,'苏格拉底复习'),h('p',{className:'rv-error',role:'alert'},loadError)):null;const c=v.card,last=v.tried.at(-1),button=(label,kind,extra)=>h('button',{type:'button',disabled:busy,onClick:()=>action(kind,extra)},label);
 const controls=[];if(!v.open){controls.push(button('复习','start'));controls.push(button('自由练习','start',{practice:true}));}else{if(c){controls.push(v.correct?button('能解释，下一张','pass'):button('提示','hint'));controls.push(button(v.correct?'还说不清':'暂时不会','skip'));}controls.push(button('收起','close'));}controls.push(h('button',{type:'button',disabled:busy,onClick:()=>setManage(!manage)},manage?'收起管理':'Anki 管理'));
 return h('section',{className:'durable-review','aria-label':'苏格拉底选择题复习'},h('div',{className:'rv-toolbar'},h('strong',{className:'rv-title'},'苏格拉底复习'),h('small',null,v.open?(v.practice?'练习 ':'复习 ')+Math.min(v.index+1,v.total)+' / '+v.total:v.totalCards+' 张 · '+v.due+' 张到期'),h('div',{className:'rv-actions'},...controls)),(error||loadError)?h('p',{className:'rv-error',role:'alert'},error||loadError):null,
 v.open?h('div',{className:'rv-body'},c?h('div',null,h('h3',null,c.question),h('div',{className:'rv-options'},...c.options.map(o=>{const tried=v.tried.includes(o.key),correct=tried&&v.correct&&o.key===last;return h('button',{key:o.key,type:'button',className:'rv-option '+(tried?(correct?'correct':'wrong'):''),disabled:busy||v.correct||tried,onClick:()=>action('choose',{choice:o.key})},(tried?(correct?'✓ ':'✕ '):'')+o.key+'. '+o.text);})),v.feedback?h('p',{role:'status','aria-live':'polite',className:'rv-feedback '+v.feedbackKind},v.feedback):null,h('small',{className:'rv-source'},'出处：'+c.source)):null,
 v.done?h('div',null,h('strong',null,v.total?'复习完成 · 独立通过 '+v.results.filter(x=>x.passed).length+'/'+v.total:'今天没有到期卡片'),h('p',null,'发送「继续上课」，老师将读取本会话成绩。'),...v.results.filter(x=>!x.passed).map(x=>h('small',{key:x.id,className:'rv-source'},'课堂复检：'+x.question))):null):null,
 manage?h('div',{className:'rv-body'},h('p',null,'当前项目卡组，会话进度分别保存。支持 11 列 Anki TSV；不支持 .apkg。'),h('div',{className:'rv-actions'},button('导出完整 TSV','export'),button('导出 Basic','export',{basic:true})),output?h('div',null,h('textarea',{'aria-label':'Anki 导出文本',readOnly:true,value:output}),h('div',{className:'rv-actions'},h('button',{type:'button',onClick:download},'下载'))):null,h('p',null,'ID / Question / A / B / C / D / Answer / Hint / Source / Explanation / Tags'),h('textarea',{'aria-label':'导入 Anki TSV',value:text,onChange:e=>setText(e.target.value),placeholder:'粘贴完整 TSV；同 ID 更新只影响当前项目卡组，不修改其他会话正在进行的轮次。'}),h('div',{className:'rv-actions'},h('button',{type:'button',disabled:busy||!text,onClick:()=>{if(confirm('确认合并到当前项目的卡组？当前会话未完成轮次将结束，旧间隔进度保留。'))action('import',{text});}},'确认合并'))):null);
}
return {inject:['slots'],apply(ctx){ctx.effect(()=>{const style=document.createElement('style');style.textContent=css;document.head.append(style);return()=>style.remove();});ctx.slots.inject('conversation.input.dock',()=>ctx.slots.register({name:'conversation.input.dock',id:'socratic-review-durable',order:5},props=>h(Panel,{key:props.sessionId,sessionId:props.sessionId})));}};
}});
